<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bootstrap_package_overrides"
 *
 * Auto generated by Extension Builder 2014-12-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Sample Bootstrap Package Overrides',
	'description' => 'Sample extension to show how to easily extend the bootstrap_package.

Primary motivation: We cannot incorporate all your cool suggestions to extend the bootstrap_package',
	'category' => 'templates',
	'author' => 'Cedric Ziel',
	'author_email' => 'cedric@cedric-ziel.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'bootstrap_package' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
